from Rollo import Rollo

rollo = Rollo()
rollo.parse("tira (3D1  +4) vantaggio")
print("______________________________________")
rollo.parse("roll (1D20+4d4) ")
print("______________________________________")
rollo.parse("tiro ( D20+ 4)")
print("______________________________________")
rollo.parse("tiro  D20+ 4)")
print("______________________________________")
rollo.parse("tiro mazunna D20+ 4)")
print("______________________________________")
rollo.parse("tiro D20 D20+ 4)")
print("______________________________________")
rollo.parse("tiro DS10 D20+ 4)")
print("______________________________________")